### ISSUE TITLE
Constant groups are under-specified and/or nonconsecutive

### ISSUE THREAD

**Issue by komiga** [jteeuwen/spirv#24]
It is unclear whether some groups are bitflags or simply enumerations. We can't do much about this except semantic inference (non-ideal) and waiting for the specification to be improved.

This makes validation harder. For nonconsecutive, non-bitflag groups, we have to switch/compare against all values, or compare against consecutive ranges. For nonconsecutive bitflag groups, we have to use hefty masks of all values (where, if they were consecutive, we could easily validate against the range). Neither are ideal.

I'll make the necessary changes and inferences for the few confusing groups, and in the mean time we can hope Khronos takes heed ([Bug 1307](https://www.khronos.org/bugzilla/show_bug.cgi?id=1307)).

**Comment by jteeuwen** [comment]
As mentioned upstream, there's some work to be done on fixing this.

I'll close this for now as we have an adequate work-around implemented.
Once the final spec is released, all the constants need to be revisited anyways.
