### ISSUE TITLE
OpCode Typos

### ISSUE THREAD

**Issue by Philip-Trettner** [jteeuwen/spirv#30]
I'm not trying to be picky but I noticed two typos/inconsistencies in the opcode enumeration:

* opcodeArraylength -> opcodeArrayLength
* opcodeInboundsAccessChain -> opcodeInBoundsAccessChain

**Comment by jteeuwen** [comment]
No worries. There's bound to be more of those kind of things and I appreciate you mentioning them.
I'll fix em a.s.a.p.

Thanks!
