### ISSUE TITLE
Should OpNop be implemented?

### ISSUE THREAD

**Issue by komiga** [jteeuwen/spirv#5]
The specification gives a definition for it:

Word Count | Opcode
---------- | ------
1 | 0

But its description says:

>Use is invalid.

So I'm not sure if we're supposed to implement this. I can't find any other documentation on the instruction.

The question is whether it's saying its presence in a module is invalid or the *execution/interpretation* of the instruction is invalid.

Ultimately, I can only see this being properly disambiguated by a revision to the specification.

**Comment by jteeuwen** [comment]
There are a few of those kind of ambiguities in the spec at this point.

I will be implementing it for completeness sake and add a TODO note as I've done in some other places. Hopefully the final version of the spec addresses it.

**Comment by jteeuwen** [comment]
Come to think of it, if this instruction is not allowed, the decoder and encoder should simply check for its use as an opcode. This is already the case when we look up a suitable codec in the instruction set. Any opcode not in there will yield an appropriate error.

**Comment by jteeuwen** [comment]
Well, I've added it in 6989567bc0c5782f390dd0cf92e011c7a3c1eb47
Probably best to just stick with spec on this. We'll see where this goes in the final version.

**Comment by komiga** [comment]
>Any opcode not in there will yield an appropriate error.

I did notice that it will be caught by the current error for lookup miss, but if it is forbidden, it'd be more accurate to explicitly check for the `OpNop` opcode and fail with a more accurate message. Unless (for some reason) someone wanted to define a codec to capture OpNops, despite their invalidity.

**Comment by komiga** [comment]
>Well, I've added it in 6989567

Oh, that works.
