### ISSUE TITLE
Instruction opcodes are duplicated between InstructionSet.BindDefault() and instruction definitions

### ISSUE THREAD

**Issue by komiga** [jteeuwen/spirv#6]
It's a bit unsavory, but I can see a few arguments for it. `InstructionSet` maps opcodes to instruction definitions (`Codec` in this case), so it makes some sense for it to be independent (e.g., one may have multiple opcodes pointing to the same definition, for whatever strange reason).

However, it makes room for non-obvious mistake: accidental disparity between the mapping and the result of `Instruction.Opcode()`. Does it make sense to supply the opcode when binding through `Codec` or by some other means, even if only to move the duplication to a single file (the instruction definition)?

**Comment by jteeuwen** [comment]
I agree. I've spent a lot of time trying out different ways to do this. Ideally all the information about an instruction should be contained in the Codec.

You have a point though. I can't make the opcode part of the Codec, as this would not help the Encoder. But I can at least have the `NewOpXXX` functions return a Codec + opcode instead of just the Codec.
This way, we'll still have the opcode listed 3 times, but at least they are all in the same file.

**Comment by jteeuwen** [comment]
Initially I had a setup like this:

```go
type Codec struct {
	Opcode uint32
	Decode func(argv []uint32) (Instruction, error)
	Encode func(Instruction, []uint32) error
}
```

I'd love this to be the only place where the opcode is hard coded.
It would remove the need to pass the opcode explicitely to `InstructionSet.Set`.

For the decoders, this works just fine. The `InstructionSet` type can retain a simple list of codecs, sorted by the opcode. Looking up codecs during decoding can be fast and easy.

The Encoder is the problem child though. It gets an `Instruction` type as input. Without a clear mapping between this type and its respective `Codec`, there is no way for it to get to the opcode cleanly.
The solution here is what we're currently doing: get the opcode from the `Instruction.Opcode` method. 
This still requires the opcode to be listed twice though. It's messy, but restricted to a single file.

Another 'solution' is this:

```go
type OpCompileFlag string

func (c OpCompileFlag) Opcode() uint32 { return 218 }

func NewOpCompileFlag() (uint32, Codec) {
	return OpCompileFlag{}.Opcode(), Codec{
		Decode: func(argv []uint32) (Instruction, error) { ... },
		Encode: func(i Instruction, out []uint32) error { ... },
	}
}
```

The `NewOpCompileFlag` can return both the opcode and `Codec` and get the opcode by creating an instance of the instruction. Frankly this is just as messy, but the upshot is that we now have the hardcoded opcode in only 1 location and everything else works as intended.

**Comment by jteeuwen** [comment]
I've removed all the opcode duplication. This implementation is not as clean as I'd like it to be, but I think it's the best we can do. Things are also not unnecessarily complicated. Which is always a bonus.
